### ISSUE TITLE
Include system dependencies

### ISSUE THREAD

**Issue by sckott** [ropensci/roregistry#1]
@cboettig what other information should be included for each pkg

**Comment by cboettig** [comment]
Thinking about how we can make this consistent with the stuff @gaborcsardi is doing on metacran.  e.g. might be fun to capture system dependencies where possible.  the rOpenSci suite is a good size to experiment with this stuff I think, complex but not too complex.

**Comment by sckott** [comment]
right, we can get information from metacran (assuming he's planning on exposing an API) but that won't help with pkgs in development

**Comment by cboettig** [comment]
right, I wasn't suggesting we necessarily get the information from metacran
so much as that we include the same fields.  for instance, the system
dependencies would be worth including, since it would help design
installations that made sure to have all the libxml and libgdal libraries
etc etc installed.

**Comment by sckott** [comment]
agreed

**Comment by maelle** [comment]
The property exist but it should be something else than a string to be useful. An array? 

Not sure how one could then validate the values. It'd be a pity for instance to have "gdall" instead of "gdal".

**Comment by sckott** [comment]
right, probably an array, right, would be best to validate somehow - what does R-hub do for system deps?

note that that our registry.json file has no system deps info in it yet

**Comment by maelle** [comment]
I've now investigated this a bit.

* Package authors should fill _SystemRequirements_ in DESCRIPTION. I've only looked at two examples, [`magick`](https://github.com/ropensci/magick/blob/master/DESCRIPTION#L19) and [`cleanNLP`](https://github.com/statsmaths/cleanNLP/blob/master/DESCRIPTION#L34).

* R-hub has a package for installing system dependencies, [`sysreqs`](https://github.com/r-hub/sysreqs). One can see the list of all possible dependencies via [this website](https://sysreqs.r-hub.io/) which was actually created at the unconf 2015 (it's written on the website). Not sure yet whether / where there are good practices for package authors.

**Comment by maelle** [comment]
Some clues in [Writing R extensions](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html) but scattered, no general guidelines as far as I can tell.

**Comment by maelle** [comment]
@jeroen what are your tips/method for using _SystemRequirements_?

**Comment by jeroen** [comment]
In what context? I use https://sysreqs.r-hub.io api which is powered by https://github.com/r-hub/sysreqsdb to find out which apt/brew packages provide a certain dependency.

**Comment by maelle** [comment]
I'd like to provide guidance to rOpenSci package authors to format _SystemRequirements_ in the best possible way (for automatic installations, for humans). We also want that info in the registry, so it'd be good if the different rOpenSci packages declared the same dependency in the same way.

So you look at the sysreqs to add the apt/brew in parenthesis? Any other tip?

**Comment by jeroen** [comment]
It's much more important to check for the sysreq in the configure script and give a helpful error message if it cannot be found.

**Comment by maelle** [comment]
Cf https://github.com/ropensci/codemetar/issues/147

Now `codemetar` gets system requirements from sysreqs DB using the package name and its SystemRequirements field, thanks to Jeroen. Currently this only outputs the URL from sysreqs directly but can/will be improved.

**Comment by sckott** [comment]
nice!

**Comment by maelle** [comment]
I need to extract all SystemRequirements of ropensci+ropenscilabs packages and see whether they are parsed via the `codemetar` sysreqsdb code and if not I might make a few PRs to sysreqsdb.

**Comment by maelle** [comment]
@jeroen should all pkgs that have SystemRequirements have a configure script? E.g. https://github.com/ropensci/ijtiff?

**Comment by jeroen** [comment]
Officially, yes they should. But for system requirements that are almost always installed, it can work without.

**Comment by maelle** [comment]
if we store the raw CodeMeta somewhere cf e.g. https://github.com/ropensci/roregistry/blob/ex/codemeta.json one can get SystemRequirements. E.g. for `magick`

``` r

cm <- jsonlite::read_json("https://github.com/ropensci/roregistry/blob/ex/codemeta.json?raw=true")
cm <- cm[lengths(cm) > 0]
magick <- cm[purrr::map_chr(cm, "identifier") == "magick"][[1]]
magick$softwareRequirements
#> [[1]]
#> [[1]]$`@type`
#> [1] "SoftwareApplication"
#> 
#> [[1]]$identifier
#> [1] "Rcpp"
#> 
#> [[1]]$name
#> [1] "Rcpp"
#> 
#> [[1]]$version
#> [1] ">= 0.12.12"
#> 
#> [[1]]$provider
#> [[1]]$provider$`@id`
#> [1] "https://cran.r-project.org"
#> 
#> [[1]]$provider$`@type`
#> [1] "Organization"
#> 
#> [[1]]$provider$name
#> [1] "Comprehensive R Archive Network (CRAN)"
#> 
#> [[1]]$provider$url
#> [1] "https://cran.r-project.org"
#> 
#> 
#> [[1]]$sameAs
#> [1] "https://CRAN.R-project.org/package=Rcpp"
#> 
#> 
#> [[2]]
#> [[2]]$`@type`
#> [1] "SoftwareApplication"
#> 
#> [[2]]$identifier
#> [1] "magrittr"
#> 
#> [[2]]$name
#> [1] "magrittr"
#> 
#> [[2]]$provider
#> [[2]]$provider$`@id`
#> [1] "https://cran.r-project.org"
#> 
#> [[2]]$provider$`@type`
#> [1] "Organization"
#> 
#> [[2]]$provider$name
#> [1] "Comprehensive R Archive Network (CRAN)"
#> 
#> [[2]]$provider$url
#> [1] "https://cran.r-project.org"
#> 
#> 
#> [[2]]$sameAs
#> [1] "https://CRAN.R-project.org/package=magrittr"
#> 
#> 
#> [[3]]
#> [[3]]$`@type`
#> [1] "SoftwareApplication"
#> 
#> [[3]]$identifier
#> [1] "curl"
#> 
#> [[3]]$name
#> [1] "curl"
#> 
#> [[3]]$provider
#> [[3]]$provider$`@id`
#> [1] "https://cran.r-project.org"
#> 
#> [[3]]$provider$`@type`
#> [1] "Organization"
#> 
#> [[3]]$provider$name
#> [1] "Comprehensive R Archive Network (CRAN)"
#> 
#> [[3]]$provider$url
#> [1] "https://cran.r-project.org"
#> 
#> 
#> [[3]]$sameAs
#> [1] "https://CRAN.R-project.org/package=curl"
#> 
#> 
#> [[4]]
#> [[4]]$`@type`
#> [1] "SoftwareApplication"
#> 
#> [[4]]$identifier
#> [1] "https://sysreqs.r-hub.io/get/libmagic"
#> 
#> 
#> [[5]]
#> [[5]]$`@type`
#> [1] "SoftwareApplication"
#> 
#> [[5]]$identifier
#> [1] "https://sysreqs.r-hub.io/get/magick++"
#> 
#> 
#> [[6]]
#> [[6]]$`@type`
#> [1] "SoftwareApplication"
#> 
#> [[6]]$identifier
#> [1] "https://sysreqs.r-hub.io/get/imagemagick"
```

<sup>Created on 2018-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.0 (2018-04-23)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  tz       Europe/Paris                
#>  date     2018-11-05                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version    date       source                        
#>  assertthat    0.2.0      2017-04-11 CRAN (R 3.5.0)                
#>  backports     1.1.2      2017-12-13 CRAN (R 3.5.0)                
#>  base64enc     0.1-3      2015-07-28 CRAN (R 3.5.0)                
#>  callr         3.0.0      2018-08-24 CRAN (R 3.5.1)                
#>  cli           1.0.1      2018-09-25 CRAN (R 3.5.0)                
#>  clisymbols    1.2.0      2017-05-21 CRAN (R 3.5.0)                
#>  crayon        1.3.4      2017-09-16 CRAN (R 3.5.0)                
#>  debugme       1.1.0      2017-10-22 CRAN (R 3.5.0)                
#>  desc          1.2.0      2018-10-04 local                         
#>  devtools      2.0.0      2018-10-19 CRAN (R 3.5.1)                
#>  digest        0.6.18     2018-10-10 CRAN (R 3.5.1)                
#>  evaluate      0.12       2018-10-09 CRAN (R 3.5.1)                
#>  fs            1.2.6      2018-08-23 CRAN (R 3.5.1)                
#>  glue          1.3.0      2018-07-17 CRAN (R 3.5.0)                
#>  htmltools     0.3.6      2017-04-28 CRAN (R 3.5.1)                
#>  jsonlite      1.5        2017-06-01 CRAN (R 3.5.1)                
#>  knitr         1.20       2018-02-20 CRAN (R 3.5.0)                
#>  magrittr      1.5        2014-11-22 CRAN (R 3.5.0)                
#>  memoise       1.1.0      2017-04-21 CRAN (R 3.5.0)                
#>  pkgbuild      1.0.2      2018-10-16 CRAN (R 3.5.1)                
#>  pkgload       1.0.1      2018-10-11 CRAN (R 3.5.1)                
#>  prettyunits   1.0.2      2015-07-13 CRAN (R 3.5.0)                
#>  processx      3.2.0      2018-08-16 CRAN (R 3.5.1)                
#>  ps            1.1.0      2018-08-10 CRAN (R 3.5.1)                
#>  purrr         0.2.5      2018-05-29 CRAN (R 3.5.0)                
#>  R6            2.3.0      2018-10-04 CRAN (R 3.5.1)                
#>  Rcpp          0.12.19    2018-10-01 CRAN (R 3.5.1)                
#>  remotes       2.0.1      2018-10-19 CRAN (R 3.5.1)                
#>  rlang         0.3.0.1    2018-10-25 CRAN (R 3.5.1)                
#>  rmarkdown     1.10       2018-06-11 CRAN (R 3.5.0)                
#>  rprojroot     1.3-2      2018-01-03 CRAN (R 3.4.3)                
#>  sessioninfo   1.0.0      2017-06-21 CRAN (R 3.4.4)                
#>  stringi       1.2.4      2018-07-23 local                         
#>  stringr       1.3.1      2018-05-10 CRAN (R 3.5.0)                
#>  testthat      2.0.1      2018-10-13 CRAN (R 3.5.1)                
#>  usethis       1.4.0.9000 2018-10-09 Github (r-lib/usethis@1e3c6a6)
#>  withr         2.1.2      2018-03-15 CRAN (R 3.4.4)                
#>  yaml          2.2.0      2018-07-25 CRAN (R 3.5.1)
```

</details>

The more or less informative aspect of the URL above depends on work in `codemetar`/R-hub sysreqsdb.

I've added some guidance about sysreqsdb to the rOpenSci development guide, since we want all package authors to make sure the system requirements they use are listed.

I'm going to close this issue.
