### ISSUE TITLE
How are the status and installable fields populated?

### ISSUE THREAD

**Issue by maelle** [ropensci/roregistry#10]
😸

**Comment by sckott** [comment]
hah, those may need to be removed. They are only done here and there where we know a package is not installable or for some reason is not "good" 

i think probably we should remove them

**Comment by maelle** [comment]
Unless we enforce real status badges? 🤔

**Comment by maelle** [comment]
`codemetar::give_opinions` will tell us/me how many package repos lack a status badge 😀

**Comment by sckott** [comment]
👌
