### ISSUE TITLE
what is the status of unconf packages?

### ISSUE THREAD

**Issue by maelle** [ropensci/roregistry#12]
Should unconf packages be in the registry? E.g. `codefinch`, `miner`... They're out-of-scope and community-contributed but live in an rOpenSci organization.

**Comment by sckott** [comment]
we do have this in our poliicies document though

> Note that not all packages developed internally by rOpenSci or through our events or collaborations are in-scope for onboarding process.

**Comment by maelle** [comment]
Yes, I was wondering whether they had a special status (like a third category?).

**Comment by maelle** [comment]
I see unconf packages like e.g. `available` are shown on the website. So should there be a property in the registry or a value of say the property contributor (community vs staff currently)? Or should they not be shown on the website and not be included in the registry?

**Comment by sckott** [comment]
well `available` didn't go through review, but is on cran, so thought it was worth including in registry. 

We might want to have a category for unconf pkgs that haven't gone through review

**Comment by maelle** [comment]
[`colorpiler`](https://github.com/ropenscilabs/colorpiler) is another example of an unconf package that's on the website.

**Comment by maelle** [comment]
What about having a value depending on _which_ unconf it was created in? I.e. the property "origin" has these values:

* staff

* community

* unconf15, unconf16 etc.

* ozunconf16, ozunconf17

**Comment by sckott** [comment]
@maelle i like that idae, sounds good to me

**Comment by maelle** [comment]
I'm wondering whether the unconf names could be keywords in DESCRIPTION, e.g. "unconf17" for `available` 🤔

**Comment by sckott** [comment]
Does make sense to have unconf + year. I guess we don''t have a way to do keywords in each codemeta file ourselves. That is, they have to come from the package itself, yes?

**Comment by maelle** [comment]
Yes!

**Comment by maelle** [comment]
Added a GitHub topic to all "unconf repos" I could identify by date of creation in ropenscilabs. This excludes repos created in ropensci for unconfs prior to 2016 of course, and is not a perfect approach.

In any case `codemetar` will get the topics as keywords in codemeta.json so we can filter/compute the unconf status from that.
