### ISSUE TITLE
Abandoned/suspended packages

### ISSUE THREAD

**Issue by maelle** [ropensci/roregistry#15]
Ideally we should get info about development status from codemeta.json in the future (via a badge in the README). In the meantime we know about some abandoned packages (e.g. `ropkgs`, `gitr`). 

* Should I create a csv of abandoned/suspended packages? Once it's validated I can also PR to the repos and add badges to their READMEs.

* Could they be _not_ mentioned on the website? It makes sense for _abandoned_, I am less sure about _suspended_ because one might want to show them in order to find potential collaborators who'd resume work: I guess in the future it'd make sense to have a status badge on the website. In the meantime, I wonder whether _suspended_ packages should be mentioned with a warning?

cc @sckott @jeroen

**Comment by sckott** [comment]
> Should I create a csv of abandoned/suspended packages? 

yeah, sounds good

> Could they be not mentioned on the website?

I think we can maybe have a badge or so if the pkg is abandoned or suspended, is that doable in the code for the pkgs page @jeroen ?

**Comment by maelle** [comment]
but even with badges doesn't it create visual clutter that makes it harder to see packages that are more active? 🤔

**Comment by sckott** [comment]
i suppose it adds more clutter - but you did make a good point that maybe someone will see a pacakge that's suspended and want to help out?

**Comment by maelle** [comment]
oh right 🤦‍♀️

**Comment by maelle** [comment]
@cboettig thinks one should use lifecycle badges instead https://github.com/ropensci/codemetar/issues/54

I haven't looked at either badges systems to make a decision but a decision needs to be taken... should you all vote at your meeting in Vancouver?

**Comment by maelle** [comment]
but in rOpenSci case how would we translate abandoned and suspended? I don't see any direct lifecycle equivalent.

**Comment by jeroen** [comment]
I think we should be able to formally "archive" packages that we no longer maintain. One way would be to move them to a special ropensci-archive org. I like keeping the `/ropensci` org clean of clutter and legacy stuff.

Alternatively we can keep them in the org and use [githubs new archiving](https://github.com/blog/2460-archiving-repositories) option.

**Comment by maelle** [comment]
so that would solve the "abandoned" state, but what about "suspended"?

**Comment by sckott** [comment]
one question i have is, do we know rstudio will at least for the foreseeable future maitain those badges? i guess we can ask the same of repostatus badges, but seems like those at least aren't tied to a company

**Comment by maelle** [comment]
I guess there could be an rOpenSci page for badge definitions, that's not too much work, if we decide on some custom ones.

**Comment by cboettig** [comment]
I think by 'abandoned' we would either mean https://www.tidyverse.org/lifecycle/#retired or https://www.tidyverse.org/lifecycle/#archived (depending on if it is replaced by a better alternative, i.e retired, or merely archived).   I think 'suspended' would be https://www.tidyverse.org/lifecycle/#dormant ?  

> I guess there could be an rOpenSci page for badge definitions, that's not too much work, if we decide on some custom ones.

I think we should use the tidyverse.org page instead?  

> do we know rstudio will at least for the foreseeable future mantain those badges? i

They are built into `usethis::use_lifecycle_badge()`, which is one reason why I think we should adopt them in favor of repostatus.org, which does not have built-in `devtools` support.  (e.g I think that's a similar argument for us using travis instead of other CI)

**Comment by maelle** [comment]
I just mentioned the possibility of an rOpenSci page in case the tidyverse one disappears. ☺

Oops sorry the one I miss is "unsupported" bc of its "up for grabs" aspect.
