### ISSUE TITLE
Installable

### ISSUE THREAD

**Issue by maelle** [ropensci/roregistry#17]
@sckott there's currently an "Installable" field which we discussed in #10 

Now with `codemetar` latest version in conIntegration one gets links to Travis/Appveyor/CircleCI pages of packages (if they have the corresponding badge in their README).

Would it make sense for me to write code to get the build status and add them to the registry? It'd be a layer we add after codemeta.json creation since CodeMeta doesn't have a term for build status.

**Comment by maelle** [comment]
Cf https://docs.travis-ci.com/user/developer/

and https://www.appveyor.com/docs/api/projects-builds/

**Comment by sckott** [comment]
> Would it make sense for me to write code to get the build status and add them to the registry?

i think so

**Comment by maelle** [comment]
I am actually surprisedthat there is no travis nor appveyor R package 🤔

**Comment by sckott** [comment]
i think there is somewhere but i never had the need - probably better to not bring in dependencies for those though anyway?

**Comment by maelle** [comment]
True!

I was wonndering whether we want a yes/no answer from each service or a nested answer if there is a matrix of builds 🤔 but i shall see when i see how the output looks like

**Comment by maelle** [comment]
There are dedicated packages actually, which might make the integration easier? And these packages might be used elsewhere?

# Travis

https://github.com/cloudyr/travisci

After authentication (uses `GITHUB_TOKEN`)
``` r
travisci::get_repo(repo = "ropensci/EML")
#> Repo (1033607): ropensci/EML
#> Active: TRUE
#> Description:  Ecological Metadata Language interface for R: synthesis and integration of heterogenous data
#> Language: 
#> Last Build (362709830) Status: passed
#> Last Build Finished: 2018-04-05T17:00:17Z
```

Created on 2018-05-07 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

# Appveyor

https://github.com/cloudyr/appveyor doesn't do much, it only returns the XML document corresponding to a query (so it'd need to be parsed).

**Comment by maelle** [comment]
Btw webhooks to CI services should be monitored because they sometimes get errors.

**Comment by maelle** [comment]
mmmh there's https://github.com/ropenscilabs/travis 🤦‍♀️
