### ISSUE TITLE
Field suggestion: latest CRAN release

### ISSUE THREAD

**Issue by maelle** [ropensci/roregistry#18]
`codemetar`/CodeMeta do not have that, there is a provider term but it'll only indicate whether the package is on CRAN/BioConductor.

Would it be interesting to know the version and date associated with the latest CRAN release using metacran?

**Comment by sckott** [comment]
we could use the crandb API https://github.com/metacran/crandb to get it, not sure if you can do an external API request though in the codemetar workflow?

e.g, http://crandb.r-pkg.org/monkeylearn

**Comment by maelle** [comment]
@cboettig there is no "latest version at provider" term right? I tend to think this field would be a layer added for our registry _after_ codemeta.json creation 🤔

**Comment by cboettig** [comment]
right.

*EDIT* just to expand on this, technically a codemeta.json file is an annotation of a single instance (i.e. single version) of software.  (just like a DOI points to a single version of a paper or dataset).  to have consistent semantics, I think you would technically want a separate file asserting the provenance relationships between different versions.  not sure if PROV has any notion of "latest", in general it seems like a dubious proposition to record in data file, at least without a timestamp associated with that assertion.

**Comment by maelle** [comment]
nowadays one could add that using `pkgsearch::cran_package()`. Not sure reg Bioconductor.

**Comment by cboettig** [comment]
Updated comment above about why this doesn't exist.  Good point about `pkgsearch()`, that sounds more reliable anyway.  

 I think we can close this?
