### ISSUE TITLE
Field suggestion: latest commit to master at the time of registry building

### ISSUE THREAD

**Issue by maelle** [ropensci/roregistry#19]
Useful yes/no?

**Comment by sckott** [comment]
im gonna say probably. can't think of a use case right now, but seems most likely useful

**Comment by maelle** [comment]
It would help with assessing repo activity for the dashboard, so could be either in the registry or only in the dashboard.

**Comment by maelle** [comment]
And also it should be used in order not to update the metadata if the commit is the same than at the latest registry build.

**Comment by maelle** [comment]
`git2r` would probably help. could go in a "complemented Codemeta.json", not sure where we'd use that, maybe for a dashboard.

**Comment by maelle** [comment]
it is present now
