### ISSUE TITLE
Use cases for the big codemeta.json

### ISSUE THREAD

**Issue by maelle** [ropensci/roregistry#23]
(and/or its complemented version cf #19 #18)

The main use of this repo is to provide JSON for ropensci.org/packages, JSON that is quite minimal.

But there might be use cases for the big codemeta.json and/or its complemented version.
* What are the biggest packages?
* Most common dependencies?
* ?

For blog posts/tech notes and what else? A dashboard? Reports?

**Comment by sckott** [comment]
what exactly is "big codemeta.json"?

**Comment by maelle** [comment]
https://github.com/ropensci/roregistry/blob/ex/codemeta.json which is mostly only the output of `codemetar::create_codemeta()`.

* It is transformed into a JSON for the packages page https://github.com/ropensci/roregistry/blob/ex/registry2.json using its own info + info from the folder (to deduce the GitHub organization in case URL is wrong in DESCRIPTION)
* potentially it could be complemented with other info (cf cf #19 #18) to become a really big JSON.

**Comment by sckott** [comment]
Yeah, that'd be neat to use it for other things.

**Comment by maelle** [comment]
Please list any application idea you have when you get a chance, to help decide whether to publish the raw big codemeta or a complemented codemeta 🙂

**Comment by maelle** [comment]
Cf also https://github.com/ropensci/codemetar/issues/118#issuecomment-436271241 cc @cboettig (I promise to repair the big codemeta.json soon :wink: )
