### ISSUE TITLE
Update categories CSV with new packages once in a while

### ISSUE THREAD

**Issue by maelle** [ropensci/roregistry#28]

**Comment by sckott** [comment]
(no need to answer now when you're on leave) what did you have in mind here? updating this i assume https://github.com/ropensci/roregistry/blob/gh-pages/final_categories.csv ? is it done manually?

**Comment by maelle** [comment]
Yes to the two last questions 😢

**Comment by sckott** [comment]
ok, thanks

**Comment by maelle** [comment]
I guess I need to update it soon.
