### ISSUE TITLE
Add ropkgs?

### ISSUE THREAD

**Issue by lmullen** [ropensci/roregistry#3]
Should the ropkgs package be added to this repository so that is added to the new drat repository for rOpenSci?

**Comment by sckott** [comment]
looks like we got it i think https://github.com/ropensci/roregistry/blob/master/registry.json#L1963-L1977

**Comment by lmullen** [comment]
Sorry, I missed that. As far as I can tell, though, ropkgs is not in the
drat repository, or at least I can't install it from there.

On Tuesday, August 11, 2015, Scott Chamberlain notifications@github.com
wrote:

> looks like we got it i think
> https://github.com/ropensci/roregistry/blob/master/registry.json#L1963-L1977
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ropensci/roregistry/issues/3#issuecomment-130103629.

## 

Lincoln Mullen, http://lincolnmullen.com
Assistant Professor, Department of History & Art History
George Mason University

**Comment by sckott** [comment]
@cboettig I don't know the answer to Lincoln's query above. `ropkgs` is in the registry, but not available via our drat apparently. thoughts?

**Comment by cboettig** [comment]
looks like we're having some issues with the aws.s3 package which isn't authenticating and uploading right now.  will see what I can do.

**Comment by cboettig** [comment]
okay, should be fixed now

**Comment by sckott** [comment]
:+1: worked for me

**Comment by lmullen** [comment]
Works for me, and this also seems to have fixed USAboundaries and
USAboundariesData. Thanks!

On Wed, Aug 12, 2015 at 8:07 PM, Scott Chamberlain <notifications@github.com

> wrote:
> 
> [image: :+1:] worked for me
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ropensci/roregistry/issues/3#issuecomment-130487179.

## 

Lincoln Mullen, http://lincolnmullen.com
Assistant Professor, Department of History & Art History
George Mason University

**Comment by sckott** [comment]
sweet, glad it works
