### ISSUE TITLE
treeio contains invalid git URL

### ISSUE THREAD

**Issue by jeroen** [ropensci/roregistry#31]
The registry gives the following URL as the git repository for the treeio package: https://yulab-smu.github.io/treedata-book/

Obviously this is not a git URL, which causes everything else in our infrastructure (docs, builds, status) to fail. This is a pretty major problem, the registry is used as the primary point of truth in our infrastructure. How can we not know the repository of the package?

**Comment by sckott** [comment]
yes, we know. working on a fix

**Comment by maelle** [comment]
What is missing @sckott? A newer codemetar version in makeregistry Remotes field in DESCRIPTION?

**Comment by sckott** [comment]
@maelle not sure what you mean by what is missing?

@jeroen the right url is there now https://github.com/ropensci/roregistry/blob/gh-pages/registry.json#L33-L46

**Comment by maelle** [comment]
I meant "what do i need to do" 😁

**Comment by sckott** [comment]
i merged the makeregistry change, and fixed a few thigns with it, seems to be working now, link above

**Comment by jeroen** [comment]
Thanks all! treeio docs are built now: https://docs.ropensci.org/treeio/
