### ISSUE TITLE
Packages with incorrect GitHub addresses

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roregistry#38]
I found two packages in the roregistry registry.json file with incorrect GitHub addresses:

```
        name                          github
1 commonmark  https://github.github.com/gfm/  # Should be https://github.com/r-lib/commonmark
2       gert https://docs.ropensci.org/gert/  # Should be https://github.com/r-lib/gert
```

**Comment by maelle** [comment]
Thank you! 

codemetar gives priority to URLs in DESCRIPTION so it picks up the first correct looking one... whereas pkgdown gives more weight to the issue tracker field.

One possible fix: changing DESCRIPTION as in https://github.com/r-lib/commonmark/pull/27

Another fix: special-case these repos in makeregistry.

Yet another fix: suggest updating the logic of {codemetar} and {codemetar}

@jeroen, what do you think?

**Comment by jeroen** [comment]
I think codemetar should be smart enough to see that the URL in `BugReports` is a GitHub URL, and the other ones are not.

**Comment by maelle** [comment]
Actually codemetar is smart enough so it must be a makeregistry problem (codemeta makes the mistake but that's another problem https://github.com/cboettig/codemeta/issues/19 as we don't use it in makeregistry)

**Comment by maelle** [comment]
ah we do use codemeta :joy:

**Comment by maelle** [comment]
https://github.com/cboettig/codemeta/pull/20

**Comment by maelle** [comment]
@steffilazerte how urgently do you need the fix?

**Comment by steffilazerte** [comment]
Not urgent, I have an easy workaround for now

**Comment by maelle** [comment]
Fixed :tada: https://github.com/ropensci/roregistry/commit/984dd49101a521ff7a6b4ca3c81bd16107718e1d

Thanks for catching and reporting this!
