### ISSUE TITLE
Should genbankr be in the registry list?

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roregistry#39]
genbankr is still (I think) an rOpenSci package, but isn't in the package registry... should it be?

It isn't under rOpenSci org, though, perhaps that's why it was missed? 
- https://github.com/gmbecker/genbankr

To be clear it is not in registry.json, but is in final_categories.csv

**Comment by maelle** [comment]
Thanks @steffilazerte! I removed it from the registry as it has been archived on Bioconductor and the maintainer hasn't expressed the desire for it to still be listed here. I had forgotten to remove it from final_categories.csv, done now!
