### ISSUE TITLE
osmapiR in packages but not registry

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roregistry#43]
osmapiR is listed in the packages.json, but not in the registry.json, is this a problem or to be expected?

**Comment by maelle** [comment]
oops, thanks, good catch

**Comment by maelle** [comment]
I can't reproduce the error locally :sob:

**Comment by maelle** [comment]
> "Error in utils::packageVersion(\"osmapiR\") : \n  there is no package called ‘osmapiR’\n"

**Comment by maelle** [comment]
https://github.com/ropensci/osmapiR/pull/51
