### ISSUE TITLE
weatherOz vs. weatheroz

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roregistry#44]
This might be incredibly nitpicky! but in the registry, weatherOz is listed as named weatheroz, but I think that's incorrect?

**Comment by maelle** [comment]
where exactly is it listed in lower-case?

**Comment by steffilazerte** [comment]
Ugh, apparently nowhere!

I would have sworn that I looked and it was lowercase in the registry.json. But I looked (even with git pickaxe, which was new to me) and there's no time the registry was lowercase 🤦🏼. My scripts/functions don't even touch the name field, so I have no idea how it happened, but even when I looked at it locally today, it was all lowercase until I restarted my session (several times!). There must be something weird I'm doing somewhere in the workflow.

Sorry about that, I'll check a bit more carefully next time 😅

**Comment by maelle** [comment]
hey no worries, especially as you catch a lot of interesting bugs!
