### ISSUE TITLE
Missing archived packages

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roregistry#46]
I've been trying to track down some discrepancies in how we calculate the number of reviewed packages in the Annual Reporting. 

One thing is that there are some packages that used to be listed in the registry/packages jsons which are no longer included. 
There is a "type" field in the registry (active, experimental, archived), so shouldn't we *always* list packages, even those archived, unless the owner requests removal?

The following have been archived, but are not listed in the registry as archived:
- Rclean
- bittrex
- bomrang
- citesdb
- cleanEHR
- dbhydroR
- getlandsat
- gtfsr
- infx
- monkeylearn
- mregions
- nbaR
- outsider
- refimpact
- ropenaq
- rromeo
- rtimicropem
- tidytags
- tabulizer

The roregistry README suggests that only packages in the `ropensci` repo are included, so this probably explains why those in `ropensci-archive` are excluded. Is this by design? Would it be possible to get all packages listed in the registry?

**Comment by mpadge** [comment]
@maelle Can you please transfer this issue to https://github.com/ropensci-org/makeregistry? Thanks!

**Comment by maelle** [comment]
Unfortunately no as we can't transfer issues across organizations. Or I suppose we could if I:

- create placeholder repo in ropensci
- transfer the issue to it
- transfer the placeholder repo to ropensci-org
- transfer the issue to the right repo
- delete the placeholder repo

Worth it?

**Comment by mpadge** [comment]
> 
> Worth it?

Nah, not worth all that trouble, when this is so much easier:

@steffilazerte Could you please close this issue here, and then paste same content into https://github.com/ropensci-org/makeregistry/issues/new? Thank you!

**Comment by maelle** [comment]
but yeah generally we haven't listed archived packages at all, the category on the website is empty. the badges data is the best truth I think at the moment.
