### ISSUE TITLE
Missing information for some active packages

### ISSUE THREAD

**Issue by steffilazerte** [ropensci/roregistry#47]
I've been trying to track down some discrepancies in how we calculate the number of reviewed packages in the Annual Reporting. 

Part of this involved finding some missing information in the registry.json:

One packages is active but unlisted: 
- MODISTools (https://github.com/ropensci/MODISTools)

Two are missing onboarding information
- medrxivr (https://github.com/ropensci/software-review/issues/380)
- rrlite (https://github.com/ropensci/software-review/issues/6)

**Comment by mpadge** [comment]
@maelle Can you please transfer this issue to https://github.com/ropensci-org/makeregistry? Thanks!

**Comment by maelle** [comment]
Reg rrlite https://github.com/ropensci/rrlite/commit/4f035c9343e2eeef620b6a98c248b7824052cfb5

**Comment by maelle** [comment]
Reg medrxivr https://github.com/ropensci/medrxivr/pull/42

**Comment by maelle** [comment]
I had excluded MODISTools https://github.com/ropensci/roregistry/commit/0c00302ba2014744ed889e78968b1bc8c8cf7112 at the maintainer's request.

**Comment by maelle** [comment]
Thanks @steffilazerte!!
